#每20分钟执行
name: bili play

on: [push]
#on:
#   gollum:
#   schedule:
#       - cron: '0,20,40 * * * *'

jobs:
  start:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: run
      run: |
        apt-get -y install xvfb gtk2-engines-pixbuf
        apt-get -y install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable
        apt-get -y install imagemagick x11-apps
        Xvfb -ac :99 -screen 0 1280x1024x16 & export DISPLAY=:99
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - 
        sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        apt-get update 
        apt-get -y install google-chrome-stable
        wget http://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
        apt-get -y install zip
        apt-get -y install unzip
        unzip chromedriver_linux64.zip
        cp chromedriver /usr/bin/
        pip install -r requirement.txt
        python main.py
