#每20分钟执行
name: bili play

on: [push]
#on:
#   gollum:
#   schedule:
#       - cron: '0,20,40 * * * *'

jobs:
  start:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: run
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i --force-depends google-chrome-stable_current_amd64.deb
        LATEST=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget http://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
        apt-get -y install zip
        apt-get -y install unzip
        unzip chromedriver_linux64.zip
        cp chromedriver /usr/bin/
        pip install -r requirement.txt
        python main.py
